# This is a basic workflow to help you get started with Actions

name: feature

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [feature/*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # configure software versions
    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout repo
      - name: Git checkout
        uses: actions/checkout@v3

      # setup Node.js
      - name: Set Node.js - v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # install angular
      - name: Install angular
        run: npm install -g @angular/cli

      # install dependencies
      - name: Install dependencies
        run: yarn

      # build angular
      - name: Build package
        run: yarn build:package

      # run tests package
      - name: Run tests package
        run: yarn test:package

        
